# 定义第一阶段，用于安装 Python 相关依赖
FROM python AS python-stage

# 安装 Python 相关依赖
# 这里可以根据需要添加或删除依赖项
RUN apt-get update && apt-get install -y --no-install-recommends \
        libexpat1-dev \
        libffi-dev \
        && \
    apt-get clean all  && \
    rm -rf /var/lib/apt/lists/*

# 定义第二阶段，用于安装 PostgreSQL 和相关依赖
FROM postgres

# 设置时区为亚洲/上海
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 安装 PostgreSQL 相关依赖
ARG DEPENDENCIES="                    \
        libexpat1-dev                 \
        libffi-dev                    \
        curl                          \
        ca-certificates               \
        vim                           \
        postgresql-15-pgvector"

RUN apt-get update && apt-get install -y --no-install-recommends $DEPENDENCIES && \
    apt-get clean all  && \
    rm -rf /var/lib/apt/lists/*

# 从 python-stage 阶段复制 Python 相关文件到当前阶段
COPY --from=python-stage /usr/local /usr/local
