# Use an image that supports armv7
FROM python

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    # Dependencies for building Python packages
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY installer/install_model.py install_model.py
RUN pip3 install --upgrade pip setuptools && \
    pip install pycrawlers && \
    pip install transformers && \
    python3 install_model.py

# Use a scratch image for the final stage
FROM scratch

# Copy the model from the first stage
COPY /opt/maxkb/app/model /opt/maxkb/app/model
