# 使用支持 armv7 的 Python 基础镜像
FROM arm32v7/python:3.11-slim AS vector-model

# Install required libraries for lxml
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxslt1-dev \
    libxml2-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# 安装依赖
RUN pip3 install --upgrade pip setuptools
RUN pip install --extra-index-url https://www.piwheels.org/simple pycrawlers
RUN pip install --extra-index-url https://www.piwheels.org/simple transformers
RUN pip install --extra-index-url https://www.piwheels.org/simple numpy

# 拷贝安装模型的脚本
COPY installer/install_model.py install_model.py

# 运行安装模型的脚本
# RUN python3 install_model.py

# 从 vector-model 阶段复制模型到 scratch 镜像
FROM scratch
COPY --from=vector-model /model /opt/maxkb/app/model
