# 定义第一阶段，用于安装 Python 相关依赖
FROM python:3.11-alpine AS python-stage

# 安装 Python 相关依赖
# 使用 apk 命令安装依赖项
RUN apk add --no-cache libexpat-dev libffi-dev

# 定义第二阶段，用于安装 PostgreSQL 和相关依赖
FROM postgres:15.8-alpine

# 设置时区为亚洲/上海
RUN apk add --no-cache tzdata && \
    ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone

# 安装 PostgreSQL 相关依赖
ARG DEPENDENCIES="curl ca-certificates vim postgresql-15-pgvector"

# 使用 apk 命令安装 PostgreSQL 相关依赖
RUN apk add --no-cache $DEPENDENCIES

# 从 python-stage 阶段复制 Python 相关文件到当前阶段
COPY --from=python-stage /usr/local /usr/local
